
name: Build

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      max-parallel: 6
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - if: startsWith(matrix.os, 'macos')
        name: Prepare macOS notarization 
        run: |
          mkdir -p ~/.appstoreconnect/private_keys
          echo '${{ secrets.mac_api_key }}' > ~/.appstoreconnect/private_keys/AuthKey_${{ secrets.mac_api_key_id }}.p8

      - if: startsWith(matrix.os, 'ubuntu')
        name: ESLint
        run: |
          npx eslint src/*.js test/*.js

      - if: startsWith(matrix.os, 'ubuntu')
        name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v1
        with:
          snapcraft_token: ${{ secrets.snapcraft_token }}

      - name: Publish Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          mac_certs: ${{ secrets.mac_certs }}
          mac_certs_password: ${{ secrets.mac_certs_password }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
